### ISSUE TITLE
device addr is equal to 0 in ABP

### ISSUE THREAD

**Issue by starsky35** [iegomez/lds#13]
Hi,
I made successfull activation test in OTAA between lds and chirpstack server.
However, I noticed that it fails in ABP because device addr stays 0 when sending uplink frames (when reading data from redis)
I did some slight modification in the code to make it works but I am surprised that nobody reported the issue maybe I missed something in the conf.

**Comment by scartill** [comment]
Indeed, the issue looks critical enough to be noticed earlier. If you have a useful fix, could you please open a Pull Request? Thanks!

**Comment by scartill** [comment]
Please refer to merge request discussion #15
