### ISSUE TITLE
tmst parameter type issue with forwarder

### ISSUE THREAD

**Issue by starsky35** [iegomez/lds#14]
Hi,

I noticed that my chirpstack server discard uplink frames using packet forwarder from lds because tmst parameter type is wrong. Indeed it is supposed to be unsigned 32b from the spec and it is defined as uint64 in lds code.

 Name |  Type  | Function
:----:|:------:|--------------------------------------------------------------
  tmst | number | Internal timestamp of "RX finished" event (32b unsigned)

Do you confirm ?

**Comment by scartill** [comment]
Indeed. Fixed.
