### ISSUE TITLE
Use LDS as a Library / inside a script

### ISSUE THREAD

**Issue by 4br3mm0rd** [iegomez/lds#22]
Hi,

I would like to make some simulations with the device simulator (stress tests, statistical verifications, etc.).

I thought of maybe extracting the relevant parts of the code, or write an automation that would click on the UI.

Is there a better way to do it? Like using the LDS as a Library? 

How do you suggest to approach this problem?

Thank you very much!

**Comment by scartill** [comment]
Hi @4br3mm0rd 

If a script is written in golang, just use lds/lds/Device entity as a simulated device. See setDevice() function for an example how to set in up.

Regards,
Boris
