### ISSUE TITLE
Repo maintenance

### ISSUE THREAD

**Issue by iegomez** [iegomez/lds#27]
Hey, @scartill!

I've given it some thought and I don't believe I'll be doing any more changes nor will I be reviewing to this repo, I just can't find the time and there are other priorities I prefer to attend to. Since you've done some great work with it and I know some people still use the project to aid in their ChirpStack testing, I'd be happy to transfer it to you if you'd be willing. Let me know what you think, but feel no pressure at all! If you aren't able to gain ownership, I'll just archive it and put a notice for others to fork and continue any work if they think it's worth it.

Thanks again and cheers!

**Comment by scartill** [comment]
Hi @iegomez ,

I still work with LoRa to some extent, and to the date I can maintain the project, especially with people actually using it. 

I'm not sure that I have any new ideas to move forward with, but if the community generates any, I'll try to comply.

Thanks for your great work and your trust.

**Comment by iegomez** [comment]
Nice, @scartill, thanks for having my back on this one! Please feel the confidence to reach to me if you ever need a hand, want to discuss some implementation or overall just have a chat about anything: I'd love to keep collaborating and would gladly do so right now if I really had the time. I'll transfer the repo right way.

Cheers!

**Comment by scartill** [comment]
@iegomez you are very welcome! Feel free to reach me at any time via Telegram (the same nickname) with any ideas.
