### ISSUE TITLE
floating point fbos not supported

### ISSUE THREAD

**Issue by Vincent-guillon** [iegomez/lds#28]
Hi there,

I built the compiled file and I correctly have the "gui" compiled file which appears using the "make" command.
When i tried to load it with ./gui it results in the following error :

`time="2021-04-12T14:36:56+02:00" level=warning msg="[redis] missing ulFcnt key: redis: nil"
time="2021-04-12T14:36:56+02:00" level=warning msg="[redis] missing dlFcnt key: redis: nil"
time="2021-04-12T14:36:56+02:00" level=warning msg="[redis] missing join nonce key: redis: nil"
time="2021-04-12T14:36:56+02:00" level=warning msg="[redis] missing dev nonce key: redis: nil"
time="2021-04-12T14:36:56+02:00" level=error msg="redis convert error (fNwksSIntKey): redis: nil"
time="2021-04-12T14:36:57+02:00" level=fatal msg="floating point fbos not supported (attempted [(0x1909, 0x1909, 0x8d61): 0x8cd6 (0x1908, 0x1908, 0x8d61): 0x8cd6 (0x1908, 0x1908, 0x1406): 0x8cd6])"`

The 5 first error lines don't seem to be an issue for the code loading but the last one stop the window's launching.
I seaked out a fix on the web but nothing worked for me.

Can you help me please? 

PS : Sorry for the topic I'm not very familiar with the go programming language

**Informations about my environment.**

OS : Linux UBUNTU 18.04 LTS
OpenGL version : 3.3
Go version : 1.16.3 linux/amd64

**Comment by scartill** [comment]
Hi,

I believe this issue is discussed in this topic: https://todo.sr.ht/~eliasnaur/gio/49 and is highly dependent on your video subsystem hardware and software configuration. Fortunately it isn't directly related to golang.

**Comment by Vincent-guillon** [comment]
I have already see this topic but I wanted to be sure that it was related.
Thank you for your support.

**Comment by scartill** [comment]
Hi @Vincent-guillon , any news on this one?

**Comment by Vincent-guillon** [comment]
Hi @scartill ,

Sorry I forgot to mention it. The problem come from the virtualized components. On workstation the GPU of your own laptop is not passed by default and a virtualized GPU is created. However this virtualized GPU doesn't provide a satisfaying result. So I tried on Proxmox where I properly passed my GPU and it worked as a charm. I also think that it would work on my personal laptop. Thank you for your help! :)

**Comment by scartill** [comment]
Glad to know, thanks!
