### ISSUE TITLE
redis get key error

### ISSUE THREAD

**Issue by giacomocolle** [iegomez/lds#3]
I've compiled lds on osx: Redis is answering pong at ping command, GUI is ok and connection to our lora server works.

By the way at device join click on the lds gui interface I receive the following error in the built-in console:
`level=error msg="redis get key error: redis: nil"`

**Comment by iegomez** [comment]
Those messages are seen when there's no info about the device at Redis an the GetInfo() method of the device is called, e.g., when trying to join or establishing first connection. I agree they are pretty misleading and they should be changed to some notification about keys not being set yet, but if everything's working you shouldn't need to worry.

I'm looking at adding an option to manually modify keys and frame counters for debugging, so I could change the messages for some more meaningful ones when I commit that.

**Comment by iegomez** [comment]
I've just added the values editor and changed the Redis messages to warnings specifying that the keys are missing (because device is not yet activated). I'm closing the issue, but reopen it or another one if you find any trouble.
