### ISSUE TITLE
Create an executable for windows

### ISSUE THREAD

**Issue by LuighiV** [iegomez/lds#32]
It is very useful for some non-developer users to have the compiled version of the program, so adding it to the respository could be amazing.

It could be accomplished using the github actions.

**Comment by scartill** [comment]
Hi @LuighiV 

Many thanks for creating the scripts! Could you please open a Pull Request? I'm not able to create and approve the same PR, unfortunately. Thank you again.

**Comment by LuighiV** [comment]
> Hi @LuighiV
> 
> Many thanks for creating the scripts! Could you please open a Pull Request? I'm not able to create and approve the same PR, unfortunately. Thank you again.

Sure, I'm going to create it, although, I feel that it lacks of some credentials to prevent Windows warns about unknown editor. Perhaps, you could add to it.
