### ISSUE TITLE
when the device join the server, I receive this error

### ISSUE THREAD

**Issue by Norman-h** [iegomez/lds#4]
ERRO[1899] processing uplink frame error data_base64=“AAgHBgUEAwIBAAAAAAAAAAAAAMyVJYI=” error=“join-request to join-server error: unmarshal response error: invalid character ‘<’ looking for beginning of value”
Thank you !

**Comment by iegomez** [comment]
Hi, I'll need a lot more information for this: what loraserver version are you using? Are you using the default join server? Are you setting join server KEK set (not supported)? Can you provide any relevant configuration details? Are you sure you are setting the same bands, LoRaWAN version and activation methods? Maybe you misconfigured some LoRa parameters? Could you share your lds conf toml?

**Comment by Norman-h** [comment]
The lora server version may be 2.6.And I using the default join server which not set server KEK. I set band EU_863_870. LoRaWAN version is 1.1 and activation method is OTAA.
 My lds conf toml:

log_level = "info"                                                                                                                          
                                                                                                                                            
[mqtt]                                                                                                                                      
  server = "tcp://localhost:1883"                                                                                                           
  user = "admin"                                                                                                                            
  password = "admin"                                                                                                                        
                                                                                                                                            
[gateway]                                                                                                                                   
  mac = "0102030405060708"                                                                                                                  
                                                                                                                                            
[band]                                                                                                                                      
  name = "EU_863_870"                                                                                                                       
                                                                                                                                            
[Device]                                                                                                                                    
eui="0000000000000000"                                                                                                                      
address="000f6e3b"                                                                                                                          
network_session_encription_key="dc5351f56794ed3ac17c382927192858"                                                                           
serving_network_session_integrity_key="dc5351f56794ed3ac17c382927192858"                                                                    
forwarding_network_session_integrity_key="dc5351f56794ed3ac17c382927192858"                                                                 
application_session_key="7b14565ba0e30d6ced804393fd6a0dd5"                                                                                  
marshaler="json"                   
nwk_key="00000000000000010000000000000001"                                                                                                  
app_key="00000000000000010000000000000001" 
join_eui="0102030405060708"                                           
mac_version=1                      
profile="OTAA"                     
joined=false                       
skip_fcnt_check=true                                                  

[data_rate]                        
  bandwith = 125                   
  spread_factor = 10                                                  
  bit_rate = 0                     

[rx_info]                          
  channel = 0                      
  code_rate = "4/5"                                                   
  crc_status = 1                   
  frequency = 916800000                                               
  lora_snr = 7.0                   
  rf_chain = 1                     
  rssi = -57                       

[raw_payload]                      
  payload = "ff00"                 
  use_raw = false                  
  script = "\n// Encode encodes the given object into an array of bytes.\n//  - fPort contains the LoRaWAN fPort number\n//  - obj is an obj
ect, e.g. {\"temperature\": 22.5}\n// The function must return an array of bytes, e.g. [225, 230, 255, 0]\nfunction Encode(fPort, obj) {\n\t
return [\n      obj[\"Flags\"],\n      obj[\"Battery\"],\n      obj[\"Light\"],\n    ];\n}\n"
  use_encoder = true                                                  
  max_exec_time = 500                                                 
  js_object = "{\n \"Flags\": 0,\n \"Battery\": 65,\n \"Light\": 54\n}"                                                                     
  fport = 2  
[[encoded_type]]                   
  name = "Flags"                   
  value = 5.0                      
  max_value = 255.0                                                   
  min_value = 0.0                  
  is_float = false                 
  num_bytes = 1                    

[[encoded_type]]                   
  name = "Batería"                 
  value = 80.0                     
  max_value = 255.0                                                   
  min_value = 0.0                  
  is_float = false                 
  num_bytes = 1                    

[[encoded_type]]                   
  name = "Luz"                     
  value = 50.0                     
  max_value = 255.0                                                   
  min_value = -0.0                 
  is_float = false                 
  num_bytes = 1                    

[redis]                            
  addr = "localhost:6379"                                             
  password = ""                    
  db = 10

**Comment by iegomez** [comment]
I can't seem to reproduce the problem. Could you check `loraserver` version just to be sure (run `loraserver version` from the terminal)? The current master branch of `loraserver` (and other components) is the test version 3.0.0 which deprecated the json marshaler for lora-gateway-bridge, so that may be the issue. You could try changing marshaler at your `toml` or from the `gui` to `protobuf` to see if that works.

**Comment by iegomez** [comment]
Actually, that shouldn't work either as lora-gateway-bridge and loraserver mqtt topics have changed on v3.0.0. Give `protobuf` a try anyway, but also try to listen to the mqtt topics with some client to see what's getting sent.

**Comment by Norman-h** [comment]
I am so sorry. My loraserver version is 2.6. I don't know how to change marshaler and what is protobuf. When I click join button I listen to mqtt topics gateway. And I receive gateway/0102030405060708/rx {"phyPayload":"AAgHBgUEAwIBAAAAAAAAAAAAAMyVJYI=","rxInfo":{"channel":0,"codeRate":"4/5","crcStatus":1,"dataRate":{"bandwidth":125,"modulation":"LORA","spreadFactor":10,"bitrate":0},"frequency":916800000,"loRaSNR":7,"mac":"0102030405060708","rfChain":1,"rssi":-57,"size":0,"time":"2019-05-10T15:38:40+08:00","timestamp":1557473920}}

And in loraserver terminal I reveive
INFO[0110] gateway/mqtt: uplink frame received          
INFO[0110] packet(s) collected                           dev_eui=0000000000000000 gw_count=1 gw_ids=0102030405060708 mtype=JoinRequest
ERRO[0111] processing uplink frame error                 data_base64="AAgHBgUEAwIBAAAAAAAAAAAAAMyVJYI=" error="join-request to join-server error: unmarshal response error: invalid character '<' looking for beginning of value"

**Comment by iegomez** [comment]
If you check your conf file (or the GUI), you'll see there's a `marshaler` option under the `device` section. That marshaler may take values `json`, `protobuf` and `v2_json`, indicating the format in which messages are sent.

To be honest, I don't think the issue has to do with this package but with your join server (if you are using a custom one) or your loraserver configurations. I believe the error is being thrown in this method at `loraserver/internal/backend/joinserver/client.go`:
```
// JoinReq issues a join-request.
func (c *client) JoinReq(pl backend.JoinReqPayload) (backend.JoinAnsPayload, error) {
	var ans backend.JoinAnsPayload

	b, err := json.Marshal(pl)
	if err != nil {
		return ans, errors.Wrap(err, "marshal request error")
	}

	resp, err := c.httpClient.Post(c.server, "application/json", bytes.NewReader(b))
	if err != nil {
		return ans, errors.Wrap(err, "http post error")
	}
	defer resp.Body.Close()

	err = json.NewDecoder(resp.Body).Decode(&ans)
	if err != nil {
		return ans, errors.Wrap(err, "unmarshal response error")
	}

	if ans.Result.ResultCode != backend.Success {
		return ans, fmt.Errorf("response error, code: %s, description: %s", ans.Result.ResultCode, ans.Result.Description)
	}

	return ans, nil
}
```
As you see, the error comes from decoding the response from the join server which seems to be wrongly formatted.

**Comment by Norman-h** [comment]
When I change to protobuf or v2_json, the error is same.
So what can I do for this error?  I see the Payload codec(I set none) in lora spp server applications.Should I change it and how to edit it?

**Comment by iegomez** [comment]
As I said, I don't know what's wrong and I don't think it has to do with this package. 
Do you have a real device at hand to test? Does it work correctly?

**Comment by Norman-h** [comment]
No, I don't  have a real device in hand. Can you share your setting about lora app server application.
Thank you!

**Comment by iegomez** [comment]
I don't have any v2.6 deployment right now as I'm testing the newest version and I have running some older ones too, but there's nothing unusual about the configuration. In particular, I leave the default join server values as they come when running `loraserver configfile > loraserver.toml`.

**Comment by heartsing** [comment]
Recent, I try to using docker. And it's join successful but not active.Why?

**Comment by heartsing** [comment]
Thank you! I'm using docker and it can join server. But how to send data to server?
when I click **send data** button in Data box,I can't find the message in uplink frame.

**Comment by Norman-h** [comment]
Thank you! I'm using docker and it can join the server.
But when I click **send data** button in data window, I can't find the data in uplink frame.
How to send data to server?

**Comment by iegomez** [comment]
Check your loraserver logs, there could be a lot of reasons for it to fail.

**Comment by iegomez** [comment]
I just made a new release in case you want to check it out.

**Comment by Norman-h** [comment]
Sorry, I have been writing my thesis recently.
I don't know how to use the latest version, I don't know how to set the uplink topic.
When I used the previous version and I clicked the send data button. In the output windows, I receive :
processing join response. 
can't decrypt join accept lorawan :MACpayload must be of type *DataPayload
downlink error: lorawan :MACpayload must be of type *DataPayload

But the deceive is activation. And the lora app server can receive the frame. The loraserver log doesn't have any error. How can I see obj Flags Battery Light in the lora app server when I click send data button?

**Comment by heartsing** [comment]
In the latest version，I only set the uplink topic gateway/%s/rx, the lora server can reveive the data.

**Comment by iegomez** [comment]
Sorry for the late response, I've been sick for the last couple of days. Please check the [loraserver documentation](https://loraserver.io) for live data and frames related questions.

As for the downlink errors, it might very well be a difference in versions or some unsupported command (`lds` only supports regular downlinks and join accepts, everything else will be seen as an error). The uplink and downlink topics are set exactly as shown in example toml, where you set a template that includes `%s` and that gets replaced by the gateway id (or mac, whatever you want to call it). Your templates should match those of `loraserver` for uplink and downlinks (`stats` and others are not supported), which are described at their docs.

**Comment by Norman-h** [comment]
I am very sorry to hear this news.
Can I ask you another question?
When I send data to device by using RESTFul API, the data always enqueue. But the lds can't receive the data.Why?

**Comment by iegomez** [comment]
If the device was configured as class A then downlinks will only be sent once an uplink is received at loraserver.

I'll close this issue now, as all these latest questions have to do with either LoRaWAN or the Loraserver project. You'll have better luck looking for help at their [forum](https://forum.loraserver.io).
