### ISSUE TITLE
run make

### ISSUE THREAD

**Issue by Mx-Tech** [iegomez/lds#5]
Dear Ignacio,
I tried to run the "make" command in the lds folder, but it stops with an TLS authentication problem.
I fixed it by reinstalling "Go", with this manual:

- https://github.com/golang/go/wiki/Ubuntu

for Ubuntu 18.04 LTS

Maybe you want to put it in your "read.me", so anyone can use it directly.

Best Wishes
Max

**Comment by iegomez** [comment]
Hey, Max. Could you share how you installed Go before the issue and the exact error?
I think it might have been an issue with your prior installation and without the details I can't generalize and include it in the docs.

**Comment by scartill** [comment]
@Mx-Tech Max, are there any updates?

**Comment by Mx-Tech** [comment]
Hi,no updates from my sideAm 23.04.2020 19:44 schrieb Boris Resnick <notifications@github.com>:
@Mx-Tech Max, are there any updates?
