### ISSUE TITLE
i need some help for use this simulator.

### ISSUE THREAD

**Issue by OniremE** [iegomez/lds#8]
Hi, sorry i´m newbie... i have installed the chirpstack server, bridge and app... they are running now and i need some help for connect it with the "Loraserver device simulator". 
I think the messages are published on my server, but I can't..
It`s my con.toml
#Configuration.
log_level = "info"

[provisioner]
	hostname = "https://example.com"
	username = "username"
	password = "password"
	path = "path/to/devices.csv"

[mqtt]
  server = "tcp://localhost:1883"
  user = "username"
  password = "password"
  uplink_topic="gateway/03004a527e341cb9/event/up"
  downlink_topic="gateway/03004a527e341cb9/command/down"

[gateway]
  mac = "03004a527e341cb9"
[band]
  name = "AU_915_928"

[device]
  eui="2e640e99456a3bf5"
  address="01cfada6"
  network_session_encription_key="dc5351f56794ed3ac17c382927192858"
  serving_network_session_integrity_key="dc5351f56794ed3ac17c382927192858"
  forwarding_network_session_integrity_key="dc5351f56794ed3ac17c382927192858"
  application_session_key="ec1b4ccf453ebeaf7d388092fb846b20"
  marshaler="json"
  nwk_key="77f1c2393bfa664daf4173f73f776688"
  app_key="ec1b4ccf453ebeaf7d388092fb846b20"
  join_eui="0000000000000002"
  mac_version=1
  profile="ABP"
  joined=false
  skip_fcnt_check=true

[data_rate]
  bandwith = 125
  spread_factor = 10
  bit_rate = 0

[rx_info]
  channel = 0
  code_rate = "4/5"
  crc_status = 1
  frequency = 916800000
  lora_snr = 7.0
  rf_chain = 1
  rssi = -57

[raw_payload]
  payload = "ff00"
  use_raw = false
	script = "\n// Encode encodes the given object into an array of bytes.\n//  - fPort contains the LoRaWAN fPort number\n//  - obj is an object, e.g. {\"temperature\": 22.5}\n// The function must return an array of bytes, e.g. [225, 230, 255, 0]\nfunction Encode(fPort, obj) {\n\treturn [\n      obj[\"Flags\"],\n      obj[\"Battery\"],\n      obj[\"Light\"],\n    ];\n}\n"
  use_encoder = true
  max_exec_time = 500
  js_object = "{\n \"Flags\": 0,\n \"Battery\": 65,\n \"Light\": 54\n}"
  fport = 2

[[encoded_type]]
  name = "Flags"
  value = 5.0
  max_value = 255.0
  min_value = 0.0
  is_float = false
  num_bytes = 1

[[encoded_type]]
  name = "Batería"
  value = 80.0
  max_value = 255.0
  min_value = 0.0
  is_float = false
  num_bytes = 1

[[encoded_type]]
  name = "Luz"
  value = 50.0
  max_value = 255.0
  min_value = -0.0
  is_float = false
  num_bytes = 1

[redis]
  addr = "localhost:6379"
  password = ""
  db = 10

[window]
  width = 1200
  height = 1000

[forwarder]
  nserver = "192.168.5.71"
  nsport = "1680"

**Comment by scartill** [comment]
@OniremE Could you please provide you configuration and the contents of your log window?

**Comment by OniremE** [comment]
the output is:
![Captura de pantalla de 2020-03-02 12-48-45](https://user-images.githubusercontent.com/58661487/75702982-93015d00-5c84-11ea-816d-ab40b115211b.png)
my chirpstack-appication-server.toml:
[general]
log_level=4

[postgresql]
dsn="postgres://chirpstack_as:dbpassword@localhost/chirpstack_as?sslmode=disable"

  [application_server.external_api]
  jwt_secret="verysecret"

**Comment by OniremE** [comment]
ok i solved it for now. just bad configurations.
